---

# - name: Check if Galaxy is managed by supervisor
#   supervisorctl: name="galaxy:" state=present
#   register: supervisor_galaxy
#   ignore_errors: yes
#   become: yes
#   become_user: root
# 
# # All of the following includes are in the tasks folder
# 
# - name: Restart Galaxy (in docker container)
#   import_tasks: restart_galaxy_docker.yml
#   when: galaxy_runs_in_docker|bool
# 
# - name: Restart Galaxy (run.sh method)
#   import_tasks: restart_galaxy_run_sh.yml
#   when: supervisor_galaxy.failed is defined and not galaxy_runs_in_docker|bool
# 
# - name: Restart Galaxy (supervisor method)
#   import_tasks: restart_galaxy_supervisor.yml
#   when: supervisor_galaxy.failed is undefined and not galaxy_runs_in_docker|bool

- name: Restart galaxy
  shell: /etc/init.d/galaxy restart

- name: wait for galaxy to finish startup 
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 8080
    delay: 60
    timeout: 1800

